backend:
  name: github
  repo: brunoannunciato/crrrivo-next-site
  branch: stage # Branch to update (optional; defaults to master)
media_folder: public/images
public_folder: images
collections:
  - name: "project"
    label: "Projetos"
    folder: "_content/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - label: "Tema"
        name: "theme"
        widget: "list"
        types:
          - label: 'Leo'
            name: 'leo'
            widget: object
            fields:
              - { label: Header, name: header, widget: string, default: 'Image Gallery' }
              - { label: Template, name: template, widget: string, default: 'carousel.html' }
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
          - label: 'Gol'
            name: 'gol'
            widget: object
            fields:
              - { label: Teste, name: header, widget: string, default: 'Image Gallery' }
              - { label: Teste, name: template, widget: string, default: 'carousel.html' }
              - label: Images
                name: images
                widget: list
                field: { label: Image, name: image, widget: image }
